filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.logstash:
  hosts: ["logstash:5000"]
  enabled: true

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: elastic
    password: changeme

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "changeme"

